app:
  image: php:apache
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./index.php:/var/www/html/index.php
    - ./api:/var/www/html/api
proxy:
  image: broadinstitute/openidc-proxy:latest
  links:
    - app
  ports:
    - "80:80"
    - "443:443"
  environment:
    #AUTH_REQUIRE: Require valid-user
    #AUTH_REQUIRE2: Require valid-user
    AUTH_TYPE: AuthType openid-connect
    CALLBACK_PATH: /oauth2callback
    CALLBACK_URI: https://auth.dsde-dev.broadinstitute.org/oauth2callback
    CLIENTID: 806222273987-052vgf5k2qr1ac2ul85aok2q6c36b9c1.apps.googleusercontent.com
    CLIENTSECRET: ZWVqFsPEQp1wErKNal32OVZm
    HTTPD_PORT: 80
    LOG_LEVEL: debug
    OIDC_COOKIE: prometheus_session
    OIDC_SCOPES: openid email profile https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/devstorage.full_control https://www.googleapis.com/auth/cloud-platform
    PROXY_PATH: /
    PROXY_PATH2: /api
    PROXY_URL: http://app:80/
    PROXY_URL2: http://app:80/api
    SERVER_ADMIN: devops@broadinstitute.org
    SERVER_NAME: auth.dsde-dev.broadinstitute.org
  hostname: auth.dsde-dev.broadinstitute.org
  volumes:
    - /etc/localtime:/etc/localtime:ro
    #- ./dev.conf:/etc/apache2/sites-enabled/site.conf
