app:
  image: php:apache
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./index.php:/var/www/html/index.php
    - ./api:/var/www/html/api
proxy:
  image: broadinstitute/openidc-proxy:latest
  links:
    - app
  ports:
    - "80:80"
    - "443:443"
  environment:
    AUTH_TYPE: AuthType openid-connect
    CALLBACK_PATH: /oauth2callback
    CALLBACK_URI: https://auth.dsde-staging.broadinstitute.org/oauth2callback
    CLIENTID: 44976466195-k6m933ijl1unv3jp8njkdmln319odeu8.apps.googleusercontent.com
    CLIENTSECRET: YDdJixqt37XS-x6IMKJ0fkLI
    HTTPD_PORT: 80
    LOG_LEVEL: warn
    OIDC_CLAIM: Require valid-user
    OIDC_CLAIM2: Require valid-user
    OIDC_COOKIE: prometheus_session
    OIDC_SCOPES: openid email profile https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/devstorage.full_control https://www.googleapis.com/auth/cloud-platform
    PROXY_PATH: /
    PROXY_PATH2: /api
    PROXY_URL: http://app:80/
    PROXY_URL2: http://app:80/api
    SERVER_ADMIN: devops@broadinstitute.org
    SERVER_NAME: auth.dsde-staging.broadinstitute.org
  hostname: auth.dsde-staging.broadinstitute.org
  volumes:
    - /etc/localtime:/etc/localtime:ro
